# Problem2

# Each new term in the Fibonacci sequence is generated by adding the previous two terms.
# By starting with 1 and 2, the first 10 terms will be:

# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

# By considering the terms in the Fibonacci sequence whose values do not exceed four million,
# find the sum of the even-valued terms.

#Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

#1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

#By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

def get_fib
    $fib = [1,2]
    i = 0
    while i < 4000000
         i = $fib[$fib.length-1] + $fib[$fib.length-2]
         if i < 4000000
             $fib.push(i)
         end
    end
    return $fib
end

def even_fib
    get_fib
    i = 0
    sum = 0
    while i < $fib.length
        if $fib[i]%2 == 0
            sum += $fib[i]
        end
    i += 1
    end
    return sum
end

even_fib, 1000)
