# Problem2

# Each new term in the Fibonacci sequence is generated by adding the previous two terms.
# By starting with 1 and 2, the first 10 terms will be:

# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

# By considering the terms in the Fibonacci sequence whose values do not exceed four million,
# find the sum of the even-valued terms.

def get_all_multiples(multiple1, multiple2, top)
    sum = 0
    for i in 0...top
        if i%multiple1 == 0 || i%multiple2 == 0
            sum += i
        end
    end
    sum
end

get_all_multiples(3, 5, 1000)